# Generated by Django 3.0.5 on 2020-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Avatars/%Y/%m/%d')),
                ('bio', models.CharField(blank=True, max_length=400, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_writer', models.BooleanField(default=False)),
                ('writed_posts', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'حساب ها',
            },
        ),
    ]
