# Generated by Django 3.0.5 on 2020-09-16 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='favorite_posts', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='account',
            name='read_later_posts',
            field=models.ManyToManyField(blank=True, related_name='read_later_posts', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
