# Generated by Django 4.0.4 on 2022-09-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='mailchimp_subscribed',
            field=models.BooleanField(null=True),
        ),
    ]
