# Generated by Django 3.0.5 on 2020-09-16 09:49

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Subcategories/%Y/%m/%d')),
                ('image_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('post_count', models.IntegerField(default=0)),
                ('timestamp', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('main_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی های فرعی',
            },
        ),
    ]
