# Generated by Django 3.0.5 on 2020-09-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='post_count',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='posts',
            field=models.ManyToManyField(related_name='subcategory_post', to='posts.Post'),
        ),
    ]
