# Generated by Django 3.0.5 on 2020-09-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0001_initial'),
        ('posts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategories_count',
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(related_name='category_post', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(related_name='category_subcategory', to='subcategories.Subcategory'),
        ),
    ]
